'use client'

import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { BrowserRouter, Routes, Route } from "react-router-dom";
import Home from '@/components/Home'
import AddNew from '@/components/AddNew'
import Edit from '@/components/Edit'


// const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    // <body className={inter.className}>
    <html lang="en" >
    <BrowserRouter>
      <Routes>
        <Route path="/" element={<Home />} />
          <Route path="/add-new" element={<AddNew />} />
          <Route path="/edit" element={<Edit />} />
      </Routes>
    </BrowserRouter>
    </html>
    // {children}</body>
  )
}
